

" some custom commands
"
" insert mom templates
command Tmomc :r ~/.vim/templates/chapter.mom
command Tmomg :r ~/.vim/templates/general.mom
command Tmomr :r ~/.vim/templates/recipe.mom
command Tmome :r ~/.vim/templates/english.mom
command Tmd   :r ~/.vim/templates/md.html
command Tman  :r ~/.vim/templates/man.1
command Tmh   :r ~/.vim/templates/man.html

" run groff+refer on file
:command Groff w|!sh -c 'p="%"; refer -PS -e -p ~/Documents/bib ${p::-4}.mom | groff -mom -Tpdf > ${p::-4}.pdf'
:command Grofft w|!sh -c 'p="%"; refer -PS -e -p ~/Documents/bib ${p::-4}.mom | groff -mom -T ascii | sed -b "s/\x1b[^m]*m//g" > ${p::-4}.txt'
:command Man w|!sh -c 'p="%"; mandoc -T html "$p" | tail -n +17 | cat ~/.vim/templates/man.html - > "$p".html'
:command Tex w|!sh -c 'p="%"; pdflatex "$p"'

:command Md !p="%"; cmark --unsafe ${p::-3}.md | h2p - ${p::-3}.pdf 

" nice line numbers
set number
set relativenumber

" syntax hilighting
syntax on
color pablo

" vimwiki
set nocompatible
filetype plugin on

" vimrc sane defaults

filetype plugin indent on
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

" fmt stuffs
set textwidth=60
set formatoptions-=t


