#!/bin/bash

sxhkd -c ~/.config/berry/sxhkdrc &

xrandr --listmonitors | grep -q 'Virtual-1 1024/271x768/203+0+0' &&
	xrandr --output Virtual-1 --mode 1360x768

feh --randomize --bg-fill ~/Pictures/wall

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 4
berryc title_height       20
berryc top_gap            20

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   56aa79
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place            "true"
berryc draw_text              "true"
berryc edge_lock              "true"
berryc set_font               "Dina-9"
